name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Ibmcloud installer
        run:  curl -sL https://ibm.biz/idt-installer | bash
      - name: multiline script
        run: |
          ibmcloud login -a cloud.ibm.com --apikey ${{ secrets.ibmapikey }} -r us-south -g Default
          ibmcloud ks cluster config --cluster bn1mshrd0o9ielralfi0
          kubectl version --short
          kubectl get namespace
          git clone https://github.com/ajayswal/jenkins1.git
          ls -al jenkins1/
