name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ajayswal1/ajayswal/ibm_env_image
    steps:
      - name: Ibmcloud installer
        run:  curl -sL https://ibm.biz/idt-installer | bash
      - name: multiline script
        run: |
          ibmcloud login -a cloud.ibm.com --apikey ${{ secrets.IBM_APIKEY }} -r us-south -g Default
          ibmcloud target -o twcoap@us.ibm.com
          ibmcloud target -s dev
          ibmcloud ks cluster config --cluster ${{ secrets. CLUSTER_ID }}
          kubectl version --short
          kubectl get namespace
          git clone ${{ secrets.GIT_CKECKOUT }}
          ls -al jenkins1/
          pwd

          kubectl create -f jenkins1/jenkins-deployment.yaml -n gitaction
          kubectl get namespace
          kubectl get deployment -n gitaction
