name: shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Ibmcloud installer
        run:  curl -sL https://ibm.biz/idt-installer | bash
      - name: multiline script
        run: |
          ibmcloud login -a cloud.ibm.com --apikey ${{ secrets.IBM_APIKEY }} -r us-south -g Default
          ibmcloud
          ibmcloud ks cluster config --cluster ${{ secrets.CLUSTER_ID }}
          kubectl version --short
          kubectl get namespace
          git clone ${{ secrets.GIT_CKECKOUT }}
          ls -al jenkins1/
